name = "Spectral Shift"
love_version = "11.5"
default_targets = ["win32", "win64"]
build_directory = "../dist"
love_files = [
    "+*",
    "-*/.*",
]
icon_file = "assets/icon.png"

[windows.exe_metadata]
FileDescription = "Spectral Shift"
FileVersion = "1.0"
CompanyName = "Keyslam"
LegalCopyright = "Copyright © 2024 Justin van der Leij"
ProductName = "Spectral Shift"
